[[section-introduction-and-goals]]
== Introduction and Goals

Despite widespread use, there are still many misconceptions and uncertainties for Baloise employees engaging in Open Source. Questions on legal issues, licensing and what is deemed confidential or internal information is common.

This document is therefore a guide, primarily for Baloise employees, on how to adopt, modify and release Open Source code. There are a few references to internal Baloise sites or services, but with an effort to limit our use of internal resources.

=== Requirements Overview



=== Quality Goals

==== Code of Conduct

Meet Corporate Governance guidelines such as https://www.baloise.com/en/home/about-us/corporate-governance.html[the general group compliance and our code of conduct].


=== Stakeholders

[options="header",cols="2,1,2"]
in alphabetical order by role / name

|===
| Role/Name | Contact | Expectations
| https://www.baloise.com/en/home/about-us/organisation.html#anchor-id-9e6b[Head of Finance & Risk] | https://github.com/UrsBienz[Urs Bienz] | Learn and share are our first steps afterwards the sky is the limit.
| https://www.baloise.com/en/home/about-us/organisation.html#anchor-id-9e6b[Head of Group Legal & Tax] | Andreas Burki |
| https://www.baloise.com/en/home/about-us/organisation.html#anchor-id-9e6b[Head of Group Strategy & Digital Transformation] | https://github.com/honeggera[Adrian Honegger] |
| Head of Product Management - Group Life Insurance and Legal Service PM | https://github.com/ThomasSchoeb[Thomas Schöb] | I'm looking forward to great ideas by "outsiders", who help us improving customer experience.
|===
