[[section-solution-strategy]]
== Solution Strategy

=== Using Open Source

Most open source code can be used in Baloise projects, but everyone has a responsibility to ensure that we respect and comply with the <<section-licenses>>.

=== Contributing to Open Source

We encourage participation in open source projects and strive to have as few rules for this as possible, we expect participants to follow common sense on what code and information they contribute - if in doubt, contact the open source team, or talk to your project lead.

==== Summary

* We encourage contributions upstream
* Make sure you don't share confidential information
* Don't contribute code which gives us an edge over competitors

==== Common contribution rules

* Do not share customer data or confidential Baloise information
* Code that cannot be contributed upstream
  * confidential source code
  * functionalities that give us an edge over competitors
* Remember that the Baloise Group legally has ownership over your contributions as you are an employee of Baloise

==== Non-code contributions

Contributions such as reporting issues, writing documentation, reviewing code and participating
in project maintenance such as creating roadmaps, grooming backlogs etc.

These activities are all sanctioned and encouraged as part of your employment at Baloise.

==== Code contributions

Upstream code contributions are also encouraged and is a natural extension of our dependency of
open source projects in our tech stack. Code contributions can generally be divided into 2 categories:

* Contributions triggered by a work task: eg. a dependency have a bug or shortcoming which block your work
* Contributions on your own initiative

Both are sanctioned and does not require a review. Simply ensure that the project you are contributing to is not licensed under AGPL.

=== Releasing as Open Source

This is the process for how Baloise employees release a new open source project on the https://github.com/baloise[Baloise] Github Organization. The process is simple and the open source team is ready to help you every step of the way.

The level of ownership as in many open source projects and communities is also for us based on http://oss-watch.ac.uk/resources/meritocraticgovernancemodel[meritocratic principles].

==== Overview

Releasing a new open source project is a simple and fast process when you are already following Baloises rules of play:

* Get Sign-off: Ensure you have organizational buy-in from your lead and that your project is possible to open source 
* Be Compliant: Ensure your project is compliant with rules of play and open source best practices
* Prepare your repository: Clean up and refactor your code to work outside the Baloise environment.
* Get Reviewed: The Baloise open source review group is responsible for reviewing your project

==== Get Sign-off  
Ensure your lead and team are onboard with open sourcing your project, that everyone understand the time and effort required, and that there is no competitive disadvantages to Baloise.

===== Get acceptance from your team and your lead

Make sure your team lead is informed about open sourcing a project, and that your lead is supportive of this. Open sourcing code is a process which requires time and effort, so make sure your lead and your team understand that some of your work hours will be spend maintaining this project and the community around it.

===== What cannot be open sourced?

Anything that risks Baloise’s competitive advantage is not permissible for publication on GitHub.com. This typically means technologies we build that are intrinsic to generating or reinforcing the uniqueness of our customer experience. This could include (but is not limited to):

* confidential source code
* functionalities that give us an edge over competitors

If you are in doubt, reach out to the Baloise Open Source Team or talk to your lead.


==== Be Compliant

Compliance covers the area of ensuring that we follow a safe and consistent practice for sharing and collaborating.

===== Rules of play

All open source projects must comply with the open source specific rules of play, which applies to code that any Baloise employee releases. There are 3 areas which the rules cover:

* Including the right files for licensing, documentation and ownership of the project
* Following the right procedure for how you create and release code
* Respecting and assigning copyright

===== Include the required assets

Use https://github.com/baloise/repository-template-java[new-project] as a boilerplate for the files required for your project. These files are needed to correctly communicate ownership and guidelines for the project:

1.  Create a meaningful `README.md` file, this is your most important piece of documentation
2.  Include a `docs/CODEOWNERS` file with contact information https://help.github.com/articles/about-codeowners/[who is maintaining the project]
3.  Include a `CONTRIBUTION.md` file with guidelines on how to contribute
4.  Add a `LICENSE.md` file, license must be the https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)[Apache License 2.0] with the copyright set to Baloise Group. For non-source code content we recommend using https://creativecommons.org/licenses/by/4.0/[CC BY 4.0] (e.g. https://github.com/creativecommons/creativecommons.org/blob/master/docroot/legalcode/by_4.0.txt[plain license TXT])
5.  Ensure you only use <<section-licenses>>-compatible code/dependencies

The open source team can help you setting this up during a initial review. 

===== Use proper procedure for collaboration

When the project has been released as a public project on Github the following workflows are expected of you:

1.  https://semver.org[Semantically version] project artifacts. You MUST tag all versions in GitHub with the exact version name: e.g., 0.1.0.
2.  Sign-off every commit, as per the https://developercertificate.org/[DCO] - PGP signing is not required
3.  Ensure that no credentials, private identifiers or personal data is at any time present in your repository
4.  Enforce code-reviews with at least 2 sets of Baloise eyes on all code to minimize the risk of implanted security backdoors and vulnerable code.
5. Ensure there is an active team of maintainers of at least 2 people from Baloise taking ownership of the project

===== Community best practices

Besides the rules of play, there is also a set of best practices which we highly recommend you implement.

1.  Have a https://baloise.github.io/open-source/docs/md/guides/governance.html#code-of-conduct[code of conduct] and enforce it to create a safe environment for collaboration
2.  Set clear expectations for responses - let users know if your time is limited
3.  Ask for help and be open to what kind of contributions would help your project
4.  Be mindful of your documentation

https://opensource.guide/building-community/[opensource.guide] has plenty more resources and recommendations for maintainers.

===== Copyright and ownership

Default ownership of all code released by Baloise employees are copyright Baloise Group and must be released under the Baloise GitHub organizations.

The namespace to use is `com.baloise.open.*`.

==== Prepare your repository

Preparing a repository for open sourcing goes beyond ensuring it is in compliance with the rules above. This can include refactoring and documenting your code better to ensure that users and potential contributors can make sense of it.

* Ensure you do not have any tokens, passwords or confidential data in your code
* Ensure the code doesn't require any Baloise-specific infrastructure or access, so users can use in their own environment
* Ensure your code is clear and commented so newcomers can see what is going on
* Ensure your dependencies are updated and does not have any known security issues
* Ensure that it is easy to get up and running, not just on your machine

==== Get Reviewed

When you have checked off the compliance checklist and prepared your code for release, request a review from the Open Source Team who will help you setup a Github repository and sign off on open sourcing your code.

==== Release

When all the above points are in order and the review has been passed, the project is released
on Baloise-Github Organization marked as an Incubator project.